package models

func getNemesisCharacterReferences() []Reference {
	return []Reference{
		// Captain
		{
			GameId:        "nemesis",
			ReferenceId:   "CAP1",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Captain Action Deck",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "CAP2",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Captain Quest Items",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "CAP3",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Captain Starting Items",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "CAP4",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Captain Character Trait",
			PageReference: "",
			URL:           "",
		},
		// Mechanic
		{
			GameId:        "nemesis",
			ReferenceId:   "MECH1",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Mechanic Action Deck",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "MECH2",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Mechanic Quest Items",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "MECH3",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Mechanic Starting Items",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "MECH4",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Mechanic Character Trait",
			PageReference: "",
			URL:           "",
		},
		// Medic
		{
			GameId:        "nemesis",
			ReferenceId:   "MED1",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Medic Action Deck",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "MED2",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Medic Quest Items",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "MED3",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Medic Starting Items",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "MED4",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Medic Character Trait",
			PageReference: "",
			URL:           "",
		},
		// Pilot
		{
			GameId:        "nemesis",
			ReferenceId:   "PIL1",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Pilot Action Deck",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "PIL2",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Pilot Quest Items",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "PIL3",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Pilot Starting Items",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "PIL4",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Pilot Character Trait",
			PageReference: "",
			URL:           "",
		},
		// Scientist
		{
			GameId:        "nemesis",
			ReferenceId:   "SCI1",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Scientist Action Deck",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "SCI2",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Scientist Quest Items",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "SCI3",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Scientist Starting Items",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "SCI4",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Scientist Character Trait",
			PageReference: "",
			URL:           "",
		},
		// Scout
		{
			GameId:        "nemesis",
			ReferenceId:   "SCO1",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Scout Action Deck",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "SCO2",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Scout Quest Items",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "SCO3",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Scout Starting Items",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "SCO4",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Scout Character Trait",
			PageReference: "",
			URL:           "",
		},
		// Soldier
		{
			GameId:        "nemesis",
			ReferenceId:   "SOL1",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Soldier Action Deck",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "SOL2",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Soldier Quest Items",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "SOL3",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Soldier Starting Items",
			PageReference: "",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "SOL4",
			Type:          "deck",
			Title:         "Nemesis Core Game",
			Section:       "Soldier Character Trait",
			PageReference: "",
			URL:           "",
		},
	}
}
