package models

func getNemesisRulebookReferences() []Reference {
	return []Reference{
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-GAME-SETUP",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Game Setup",
			PageReference: "p.6-9",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-EVENT-PHASE",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Event Phase",
			PageReference: "p.10",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-INTRUDER-BAG-DEVELOPMENT",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Intruder Bag Development",
			PageReference: "p.10",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-VICTORY-CHECK",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Victory Check",
			PageReference: "p.11",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-END-OF-GAME",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "End of Game",
			PageReference: "p.11",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-END-BEFORE-OTHERS",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Ending the Game Before the Other Players",
			PageReference: "p.11",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-CRITICAL-GAME-MOMENTS",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Critical Gameplay Moments",
			PageReference: "p.12",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-ACTION-COST",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Action Cost",
			PageReference: "p.12",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-ACTION-COMBAT",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "In Combat Only / Out of Combat Only",
			PageReference: "p.12",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-BASIC-ACTION",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Basic Actions",
			PageReference: "p.13",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-CARD-ACTION",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Actions from Action Cards",
			PageReference: "p.13",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-INTRUDER-ATTACK",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Intruder Attack",
			PageReference: "p.20",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-INTRUDER-INJURIES",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Intruder Injuries and Death",
			PageReference: "p.20",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-INTRUDER-WEAKNESS",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Intruder Weakness Cards",
			PageReference: "p.21",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-CONTAMINATION",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Contamination Cards",
			PageReference: "p.20-21",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-DOORS",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Door Token",
			PageReference: "p.17",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-FIRE",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Fire Markers",
			PageReference: "p.17",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-MALFUNCTION",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Malfunction Markers",
			PageReference: "p.17",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-ITEM-ACTION",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Actions from Item Cards",
			PageReference: "p.13",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-MELEE",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Melee Attack Action",
			PageReference: "p.19",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-MOVEMENT",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Movement Action",
			PageReference: "p.14",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-ROOMS-AND-CORRIDORS",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Rooms and Corridors",
			PageReference: "p.14",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-INTRUDER-MOVEMENT",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Additional Notes About Intruder Movement",
			PageReference: "p.15",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-EXPLORATION-TOKENS",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Exploration Tokens",
			PageReference: "p.14-15",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-NOISE",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Noise Roll",
			PageReference: "p.15",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-MARKER",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Noise Marker",
			PageReference: "p.17",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-TECHNICAL-CORRIDORS",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Technical Corridors",
			PageReference: "p.16",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-PLAYER-PHASE",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Player Phase",
			PageReference: "p.10",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-PLAYER-GOALS",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Player Goals",
			PageReference: "p.11",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-QUEST",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Quest Items",
			PageReference: "p.23",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-ROOM-ACTION",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Actions from Room Tiles",
			PageReference: "p.13",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-ROOMS",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Room Sheets",
			PageReference: "p.24-26",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-ENCOUNTER",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Encounter",
			PageReference: "p.18",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-COMBAT",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Combat",
			PageReference: "p.18-19",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-OBJECTS-AND-ITEMS",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Objects and Items",
			PageReference: "p.22",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-INVENTORY",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Character Hands and Inventory",
			PageReference: "p.22",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-SHOOT",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Shoot Action",
			PageReference: "p.18",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-SLIME",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Slime Markers",
			PageReference: "p.17",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-WOUNDS",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Character Wounds and Death",
			PageReference: "p.21",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-CHAR-ESCAPE",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Character Escape",
			PageReference: "p.19",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-ESCAPE-POD",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Escape Pods",
			PageReference: "p.26",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-SOLO-AND-COOP",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Solo and Cooperative Mode",
			PageReference: "p.27",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-INTRUDER-PLAYER",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Playing as an Intruder",
			PageReference: "p.27",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "R1-OBJECTIVES",
			Type:          "rulebook",
			Title:         "Nemesis Core Rulebook",
			Section:       "Objectives",
			PageReference: "p.12",
			URL:           "",
		},
		// FAQ References
		{
			GameId:        "nemesis",
			ReferenceId:   "FAQ1-ACTIONS",
			Type:          "faq",
			Title:         "Nemesis FAQs v2.1",
			Section:       "Actions",
			PageReference: "p.3",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "FAQ1-RULES",
			Type:          "faq",
			Title:         "Nemesis FAQs v2.1",
			Section:       "Rules",
			PageReference: "p.2",
			URL:           "",
		},
		{
			GameId:        "nemesis",
			ReferenceId:   "FAQ1-ROOMS",
			Type:          "faq",
			Title:         "Nemesis FAQs v2.1",
			Section:       "Rooms",
			PageReference: "p.4",
			URL:           "",
		},
		// BGG Thread References
		{
			GameId:        "nemesis",
			ReferenceId:   "BGG1-LARVA-ESCAPE",
			Type:          "bgg",
			Title:         "BGG Thread: Can't escape the Larva?",
			Section:       "Rules",
			PageReference: "",
			URL:           "https://boardgamegeek.com/thread/2126141/cant-escape-the-larva",
		},
	}
}
